language: node_js
node_js:
  - node
sudo: false
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: EQi8Vi7ciOgvjJMzZQatNQ0ZvizlDKkLzWMKaTj0YuyGpAVseEXAhV75bZDhSH6BE4A3Rj2R0DDjn/kyNhUo37nA97+hql3cdYM5hQDae1zybnLz3daic12KxlGcf0zXQ5eQSCyxBghl06dU+SdqLw/8PtG8YlKGLO9YTBhEgz4O4eSgBT9lEl3E923XgzDiSfMx72CS/EfbFNwruXGrPQRIIu2TkO2LnyIQWdOq/g09MLItdezAJSyY4h63JmRRLQt1lCJuZZp0VE5C5ny7cnz1J/6eKIXogXbFY4rDKge7jSOJoOxWNTTvw5PyverGlnHLyofSoIm4QFwROehHNSIHxbDSrHSK/1ug5SxCsew9TPLZZa0h+O4ckw4GT4d77hUmwKXJdkNqPhKbe69tKTRzuaRX4588f2+RdYw1J4xqZ3sVYYVSh0Ri6jkl2zeWMlkawbAb8hR2C46dZu9sTvWs+95HhN2swHCnQJRemGbHWd2uXaudmgm2hLT2WsofAJZe5BN/eY7Yx/0t7fwmmg5tMD3wtJTBmqg0Fi09KKDR+gIt0RxwLnzG+H+ZzlM1W974LutS0zMrLI89QJIZSfGplZeHDuAUexNPvdvj4cPYmwHCQjswUGyin71UseI+2r1EV+ksLihGKcvMJbC06MMyAu2QXXBq7nWBmYAY0Eg=
  app: gtsdevopslab21
  edge: true
